#!/bin/bash
# 安装集成nginx、php7.2、mysql的环境

if [[ ! `which php7.2` ]]; then
    curl -o- https://shell.if-she.com/ubuntu/php-install-72 | bash
    service php7.2-fpm start
fi

if [[ ! `which nginx` ]]; then
    curl -o- https://shell.if-she.com/ubuntu/nginx-install | bash
    service nginx start
fi

if [[ ! `which mysql` ]]; then
    curl -o- https://shell.if-she.com/ubuntu/mysql-install | bash
    service mysql start
fi

