#!/bin/bash
# 安装worldpress

curl -o- https://shell.if-she.com/ubuntu/_lnmp | bash

cd /var/www;

if [[ ! `which wget` ]]; then
    apt install wget -y
fi

while [[ ! -f latest-zh_CN.tar.gz ]]; do
    wget https://cn.wordpress.org/latest-zh_CN.tar.gz
done

if [[ ! `which unar` ]]; then
    apt install unar -y
fi

unar latest-zh_CN.tar.gz
rm -rf latest-zh_CN.tar.gz
chmod -R 777 wordpress

service mysql start
mysql -uroot -proot -e "create database wordpress;"
service mysql stop

read -p '您的域名：' domain


if [[ -z $domain ]]; then domain='_'; fi

(cat <<CONF
server {
    listen 80;
    server_name ${domain};
    root /var/www/wordpress;
    index index.html index.php;
    location / {
        try_files \$uri \$uri/ /index.php\$request_uri;
    }
    location ~* \.(js|css|png|jpg|jpeg|gif|ico)\$ {
        expires max;
        log_not_found off;
    }
    include enable-php7.2.conf;
}
CONF
) > nginx.conf;

cat <<HINT
现在已经成功安装了wordpress, 请在浏览器端打开您的域名或服务器IP即可

需要更多帮助可移步 https://www.if-she.com 获取相关资料

数据库名(默认即可): wordpress
用户名：root
密码: root
数据库主机: localhost
表前缀(随意)

禁用FTP方式上传请在安装完成后手动在wp-config.php末尾处添加:
define("FS_METHOD", "direct");
define("FS_CHMOD_DIR", 0777);
define("FS_CHMOD_FILE", 0777);

在添加ssl证书后某些css可能无法加载, 解决方案是在 wp-config.php 顶部添加:
\$_SERVER['HTTPS'] = 'on';
define('FORCE_SSL_LOGIN', true);
define('FORCE_SSL_ADMIN', true);
HINT